### ISSUE TITLE
Koala compilation failure

### ISSUE THREAD

**Issue by nicolasmichaeleljamal** [creativetimofficial/material-dashboard-pro#10]
Hello, After adding material-dashboard.sass to Koala and trying to compile it I am getting an error without any description. Any idea? I have no experience in front-end development. Thank you 
![screenshot 2017-02-06 23 14 01](https://cloud.githubusercontent.com/assets/9370214/22666743/82b2d12a-ecc2-11e6-87fd-6f0c662affa3.png)

**Comment by alexandru-paduraru** [comment]
@nicolasmichaeleljamal thank you for using our product. Please try to uncheck the source map and set the output style to expanded and let us know if that is working.
