### ISSUE TITLE
Im getting an error when viewing the demo;

### ISSUE THREAD

**Issue by dleblancjr** [creativetimofficial/material-dashboard-pro#11]
GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=27.12&action=apiboot2&e=10_1_0,10_2_0&rt=main.5 net::ERR_BLOCKED_BY_CLIENT

Is this something that would go away with a purchase?

Thanks,
Dexter

**Comment by alexandru-paduraru** [comment]
@dleblancjr thank you for using our product. On our side, we cannot see that issue but we think it is from the Google Maps. They blocked the content that is coming without an API Key. To set your own API key please follow this tutorial:

1. Go to https://developers.google.com/maps/documentation/javascript/get-api-key
2. Scroll to the “Get an API key” Title and press the “Get a Key” Button
3. Choose a name for your project then press on Create and Enable API
4. Get the Key and place it in your project where is this script:

`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>`

Best,
Alex
