### ISSUE TITLE
Get row data from SimpleTable

### ISSUE THREAD

**Issue by epilkis** [creativetimofficial/material-dashboard-pro#115]
Hi,
I am trying to get row data in a SimpleTable and use action buttons. If I call the DataTable() function, it converts my table from SimpleTable to DataTable. I want to manipulate table data with action buttons and keep my table appearance. There was no example in extended.html and supporting js files that I could find. 

Thanks

**Comment by epilkis** [comment]
Found the answer. In DataTable constructor pass the following values to disable extra feautures and the table becomes a SimpleTable as described in datatables.net documentation. https://datatables.net/release-datatables/examples/basic_init/filter_only.html

var table = $('#datatables').DataTable({
		"paging":   false,
                "ordering": false,
		"searching": 	false,
                "info":     false
	});

**Comment by dragosct10** [comment]
Hi! We are glad that now the problem was fixed for you. Regards, Dragos
