### ISSUE TITLE
What is the recommended way to add custom styles in CSS?

### ISSUE THREAD

**Issue by mndotmail** [creativetimofficial/material-dashboard-pro#12]
Hi,

I have created a custom stylesheet `style.css` and placed it in the root.
Unless I add `!important`, existing styles are not able to change.

I don't want to change the master CSS files `material-dashboard` & `bootstrap.min`

**Comment by alexandru-paduraru** [comment]
Hi @mndotmail thank you for using our product. You need to make sure that style.css is added after bootstrap.min.css and material-dashboard.css like this:

1. bootstrap
2. material-dashboard
3. style.css

In this order and everything will work fine. Please let us know what framework you use for development? It seems it is mess with the files' order.

Best,
Alex

**Comment by bethal** [comment]
That worked.

**Comment by mndotmail** [comment]
That worked.
