### ISSUE TITLE
Error with datetimepicker plugin

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/material-dashboard-pro#132]
Hi, by default, we can see the icons for example change the date, time, etc. On the other hand, if you want to re-configure some parameters like this in the script footer, the icons disappear:
`$('.datetimepicker').datetimepicker({
    locale: 'fr-ca'
});`

Example: [http://klam.shost.ca/test/](http://klam.shost.ca/test/)

Do you have a solution ?

Regards

**Comment by mtik00** [comment]
@KonScyence: You are creating a whole new `datetimepicker` object if you use it that way.  When doing that, you should re-create the entire object like they do in `material-dashboard.js`.

I recommend something like this:
```javascript
        $('.datetimepicker').datetimepicker({
            locale: 'fr-ca',
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
         });
