### ISSUE TITLE
Radioboxes and Checkboxes arent printing

### ISSUE THREAD

**Issue by angelcalvasp** [creativetimofficial/material-dashboard-pro#135]
When you print a page checkboxes and radio buttons dont show up on the print page or the print preview have tested this with the sample form pages in Edge, Chrome and Firefox

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! Thank you for using our product. How exactly looks the checkboxes and radio? Regards, Dragos

**Comment by angelcalvasp** [comment]
Ill upload a pic in a second to be more precise its the inner span inside the radio that doesnt show up but the shadow does

**Comment by angelcalvasp** [comment]
![image](https://user-images.githubusercontent.com/7502746/39204504-9053eb50-47bd-11e8-9aa2-843edd58534f.png)

**Comment by dragosct10** [comment]
Hi! Please set the setting of the print correctly. Backgound graphics must be checked. 

<img width="1006" alt="screen shot 2018-04-25 at 11 03 14" src="https://user-images.githubusercontent.com/17456857/39233197-5dbf07fe-4878-11e8-9fa4-cad746c1ea98.png">

Regards,
Dragos

**Comment by angelcalvasp** [comment]
Silly me thanks
