### ISSUE TITLE
vertical-nav.js is not needed?

### ISSUE THREAD

**Issue by pablodgcatulo** [creativetimofficial/material-dashboard-pro#138]
I have this code in the login.html page I just download. I think this is old code because vertical-nav is not needed anywhere. But there is a thing that is puzzling me. Why, in the online demo, the vertical-nav.js doesn't show up?
```
<!-- Plugins for presentation and navigation  -->
<script src="../../assets/assets-for-demo/js/modernizr.js"></script>
<script src="../../assets/assets-for-demo/js/vertical-nav.js"></script>
```

**Comment by dragosct10** [comment]
Hi, @pablodgcatulo! Thank you for using our product. That vertical navs are just for Material Kit so we are sorry that you find that plugin in your project, we will fix this in the next update. Regards, Dragos

**Comment by pablodgcatulo** [comment]
Thanks @dragosct10 !
