### ISSUE TITLE
 SweetAlert Issue

### ISSUE THREAD

**Issue by locmai0808** [creativetimofficial/material-dashboard-pro#139]
![image](https://user-images.githubusercontent.com/18728001/39417401-cf629d38-4c08-11e8-974b-9e0362b88674.png)
I got this issue while SweetAlert

**Comment by dragosct10** [comment]
Hi, @locmai0808! Thank you for using our product. The issue it's not from the sweet alert, it is from `bootstrap-material-design.js` and please take the uploaded js file and replace in your project to fix this problem. 
[bootstrap-material-design.js.zip](https://github.com/creativetimofficial/material-dashboard-pro/files/1966384/bootstrap-material-design.js.zip)

Regards,
Dragos

**Comment by locmai0808** [comment]
@dragosct10 Thanks Dragosct, this helped to fix it.
