### ISSUE TITLE
Tooltip styling

### ISSUE THREAD

**Issue by mndotmail** [creativetimofficial/material-dashboard-pro#14]
I have used `data-toggle="tooltip" data-placement="bottom" title="Tooltip on top"`, but showing toolyip without any styling.
Am I missing anything?

**Comment by alexandru-paduraru** [comment]
@mndotmail can you please send us a link to your website? On our side the tooltip on bottom is working fine, please check this image:

<img width="409" alt="screen shot 2017-02-15 at 21 28 19" src="https://cloud.githubusercontent.com/assets/2517758/22991652/b23fa2b0-f3c5-11e6-8459-4239690afec9.png">

Best,
Alex

**Comment by mndotmail** [comment]
Thanks Alex;  I have added `rel="tooltip"` and it worked.
