### ISSUE TITLE
Datatable not overlaps on mobile

### ISSUE THREAD

**Issue by pablodgcatulo** [creativetimofficial/material-dashboard-pro#142]
I'm having an issue with datatables on mobile on the pro version. The pagination number overlaps all over the place. Here is the capture from your online demo

![captura de pantalla de 2018-05-08 20-55-33](https://user-images.githubusercontent.com/4323948/39788859-c72eb74a-5302-11e8-9963-4ba645dadaf7.png)

Do you have a quick fix for this? 

Thanks!!!!!

**Comment by timcreative** [comment]
Hi, @pablodgcatulo! Thank you for using our product. You can put on the class `.pagination` the property `display: inline-block;` on the media query max-width: 546px.

Regards,
Dragos

**Comment by pablodgcatulo** [comment]
U are great!
