### ISSUE TITLE
 $(window).scroll doesn't seem to trigger

### ISSUE THREAD

**Issue by BrianDrought** [creativetimofficial/material-dashboard-pro#18]
Hi, am trying to implement a 'Scroll to Top' function as seen here:

https://codepen.io/rdallaire/pen/apoyx

Works fine in plain HTML, but the minute I include Material Dashboard Pro, the scroll event doesn't ever seem to trigger. That's even with disabling Perfect Scrollbar and testing on Android etc. 

Any ideas?

**Comment by BrianDrought** [comment]
Solved... that's because the window isn't scrolling, it's the div. Changed the code to this and it works lovely. 

       $('div.main-panel').scroll(function () {
                    if ($('div.main-panel').scrollTop() >= 50) {        // If page is scrolled more than 50px
                        $('#return-to-top').fadeIn(200);    // Fade in the arrow
                    } else {
                        $('#return-to-top').fadeOut(200);   // Else fade out the arrow
                    }
                });

**Comment by alexandru-paduraru** [comment]
@BrianDrought thank you for using our product and sorry for the late response. Yes, that's what I wanted to point. The body is not scrolling, the scroll is inside the `.main-panel`, it seems you figure this out. Congrats! We will add your code suggestion in the documentation so other people will know if they want to do that. Hope this is fine with you.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Changed structure of the page so scroll is triggered right now. Done in v1.2.0.
