### ISSUE TITLE
Minibar crash when height exceeds viewport

### ISSUE THREAD

**Issue by andres770105** [creativetimofficial/material-dashboard-pro#24]
When there are several items in menu, minibar visualization crashes after the viewport.

![minibar crash](https://cloud.githubusercontent.com/assets/26516246/24152362/64333582-0e19-11e7-9fad-8d5fb98c6b8a.jpg)

I´ve tried all solutions in https://github.com/creativetimofficial/material-dashboard-pro/issues/2, but none of those works the right way, because I need all menu items visible.

On the other hand, the footer should be localized at the end of the length of minibar when it exceeds the viewport, but it doesn't.

Thanks.

**Comment by dragosct10** [comment]
Hi @andres770105! Sorry for the late response. We know that sidebar-mini have a few bugs and because of this we made an update for Paper Dashboard Pro with a new sidebar-mini that resolve all the possible and existing issues with the sidebar-mini, so we also prepared an update for Material Dashboard Pro with the same sidebar-mini which will be available soon. Please check this link to see how will look the new sidebar-mini: [Paper Dashboard Pro sidebar-mini](http://demos.creative-tim.com/paper-dashboard-pro/examples/dashboard/overview.html?demo_sidebar_mini=active)

Thanks,
Dragos!

**Comment by andres770105** [comment]
Hi @dragosct! I'm really satisfied with the new mini-sidebar, it looks great and the animation is a very good option. However, 2 problems persist with the sidebar-mini scrollbar:


  1.  When the page loads on a pc, the scrollbar does not display the proper css style (see attachment).
  2.  The sidebar-mini allows horizontal scrolling, which should not happen (see attachment).

[cid:image003.jpg@01D2AC6C.899D5280]

Congratulations on everything else, it's a great step forward from the previous sidebar-mini. I want to see it soon included in the material-dashboard, is there an estimated date for this?

Thank you.


Andres Ramirez
.NET Senior Web Developer


De: dragosct<mailto:notifications@github.com>
Enviado: lunes, 3 de abril de 2017 8:35 a. m.
Para: creativetimofficial/material-dashboard-pro<mailto:material-dashboard-pro@noreply.github.com>
CC: Andres Ramirez<mailto:andres.ramirez@outlook.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [creativetimofficial/material-dashboard-pro] Minibar crash when height exceeds viewport (#24)


Hi @andres770105<https://github.com/andres770105>! Sorry for the late response. We know that sidebar-mini have a few bugs and because of this we made an update for Paper Dashboard Pro with a new sidebar-mini that resolve all the possible and existing issues with the sidebar-mini, so we also prepared an update for Material Dashboard Pro with the same sidebar-mini which will be available soon. Please check this link to see how will look the new sidebar-mini: Paper Dashboard Pro sidebar-mini<http://demos.creative-tim.com/paper-dashboard-pro/examples/dashboard/overview.html?demo_sidebar_mini=active>

Thanks,
Dragos!

**Comment by dragosct10** [comment]
Hi @andres770105! Thanks for your feedback, we identified the problem and we will fix it. For material-dashboard-pro we will come with a solution for you next week. Hope this is ok with you.

Best, 
Dragos

**Comment by andres770105** [comment]
That´s fine, thanks you all.
