### ISSUE TITLE
Checkbox is not rendered when loading from Angular template

### ISSUE THREAD

**Issue by genievn** [creativetimofficial/material-dashboard-pro#25]
Hi,

I have checkboxes in an Angular template file and loaded dynamically, but the checkboxes are not rendered. Is there a function I need to call to have material checkboxes?

Thank you!

**Comment by alexandru-paduraru** [comment]
@genievn thank you for using our product. Please add the Arrive.js library before material.min.js, here are more details from the original repository: https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support

Best,
Alex
