### ISSUE TITLE
Migrate to Bootstrap4

### ISSUE THREAD

**Issue by mndotmail** [creativetimofficial/material-dashboard-pro#26]
How can I migrate to bootstrap4 or do you have any plans to release Material Dashboard Pro with bootstrap4?

**Comment by alexandru-paduraru** [comment]
@mndotmail we have in plan to upgrade it to BS4 as soon as they release a stable Beta. At this moment we are playing with the Alpha 6 version on GSDKit, you can see the progress here: https://github.com/creativetimofficial/get-shit-done/tree/bootstrap4-development 

Stay tuned, we will upgrade all the products to BS4.

Best,
Alex
