### ISSUE TITLE
Checkbox checked rounded shadow not aligned on Firefox

### ISSUE THREAD

**Issue by noricumbo** [creativetimofficial/material-dashboard-pro#3]
Hi, I'm using Firefox 50.0 on Mac OS 10.11 and this shadow is not correctly aligned. Although in Chrome and Safari works correctly.

![screen shot 2016-11-25 at 5 58 54 pm](https://cloud.githubusercontent.com/assets/1501753/20636834/0cc686ee-b33a-11e6-8264-f63c3862e802.png)

If I modify `top` property of `.checkbox .checkbox-material::before` and set it to `-5px` it work on all browsers. But I want to know if you can check and correct this on the original files.

Thanks

**Comment by alexandru-paduraru** [comment]
@noricumbo thank you for using our product and for the information. We've checked and you're right, there is an issue with the checkbox's ripple. We noted it and will be fixed in the next release.

Best,
Alex

**Comment by noricumbo** [comment]
Thanks! Do you know when will the next release come out?

**Comment by alexandru-paduraru** [comment]
The next update will come when more issues are packed and also new features will be developed. Since the latest update was about 10 days ago and it fixed all the known issue from V1.0.0 we don't have a date prepared for v1.2.0, we need to see what are the requests from the users in order to pack for a new update :D

Here is the changelog for the latest update:

```
- V1.1.0 17 Nov, 2016 - BugFixing, Plugin Change 
- Fix bug on main panel > content while you use the Sidebar Mini 
- Replaced select plugin with a more complex select “bootstrap-select” 
- Added File Input library by Jasny 
- change filter colors for example pages 
- fix Charts responsive issue when switching from Desktop to Mobile 
- added PerfectScrollbar just for Windows, fix problem in MacOs and Ubuntu
```

Best,
Alex

**Comment by noricumbo** [comment]
Ok, I'm using this right now in a project. I'll post if I find another bug. Thank you Alex :)

**Comment by alexandru-paduraru** [comment]
@noricumbo that's great! Just let us know if you have any other issues and don't forget to share with us the final result, we would be glad to give you feedback :D
