### ISSUE TITLE
selectpicker broken in bootstrap-wizard 

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/material-dashboard-pro#30]
Hi! I checked the issue with selectpicker that breaks the `.nav-pills` from the top of the wizard and I fixed it. What you must do is to go in `assets/js/demo.js` on the line: `233`and replace the `total_steps = $wizard.find('li').length;` with `total_steps = $wizard.find('.wizard-navigation li').length;`. Hope that helps you! 

Best,
Dragos

**Comment by yonidejene** [comment]
Hi Dragos,

Thank you for the prompt response and I tried replacing that but it still does not work.

Here's what I get:

https://www.dropbox.com/s/f52gsid86ci15im/Screenshot%202017-04-04%2012.34.52.png?dl=0

**Comment by dragosct10** [comment]
HI @yonidejene! Can you please send me a link with your project to see exactly what was changed, and in this way I will fix the issue? On our side everything is working fine. 

Regards, 
Dragos

**Comment by yawkale** [comment]
demo.js line 237  just change ti this line
total_steps = $wizard.find('.wizard-navigation li').length;

**Comment by laurencei** [comment]
This solved the issue for me. 👍 

It becomes obvious if you only have 2x steps (rather than the default 3) - it clearly breaks without this change.

**Comment by iamchriswick** [comment]
I came across the same issue, and fixed it bay changing `total_steps = $wizard.find("li").length;` to `total_steps = $wizard.find(".wizard-navigation ul li").length;` in **initWizard.js**.
