### ISSUE TITLE
How to use the Full Calendar?

### ISSUE THREAD

**Issue by dbarrett24** [creativetimofficial/material-dashboard-pro#35]
How can I port in a working version of the calendar in the demo?

**Comment by alexandru-paduraru** [comment]
@dbarrett24 thank you for using our product. The FullCalendar library is a very complex one with a huge documentation which can be checked here: https://fullcalendar.io/docs/. We basically did just the design to fit with the rest of Material Dashboard PRO. So you can find more information about how to link that to your database on their documentation.

Please let us know if you have any specific question that you don't find in their documentation and if we can we will help you.

Best,
Alex
