### ISSUE TITLE
Material Dashboard Pro - Slider

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/material-dashboard-pro#36]
Hi Axelut, Where do I find information on the sliders that are in Material Dashboard Pro? I could not find any details/examples to set up the slider (e.g. horizontal/vertical, setting a step, showing values, etc). Thanks for your help.

**Comment by alexandru-paduraru** [comment]
@EricL2017 thank you for using our product and sorry for the late response. I've checked and you're right we didn't include a link to the Sliders library in the documentation. We will do that in the next release. Please find the official website here: https://refreshless.com/nouislider/

Best,
Alex
