### ISSUE TITLE
Javascript support for React Apps

### ISSUE THREAD

**Issue by rodfraga** [creativetimofficial/material-dashboard-pro#37]
Any of the javascript features of Material Dashboard Pro doesn't work in a React Web App, checkbox, radios, tooltips, charts.

**Comment by rodfraga** [comment]
The .css issue can be fixed by adding the material-dashboard.css inside the src and Import it directly, this fix the most issues.
Wizard still falling given the missing support for the external Js files. seems webpack is an approach but still unable to make it work.
The carts issue can be fixed by importing the npm chartist package, however the nice custom styling is gone, some help to recover this nice styling could be awesome from you guys.

**Comment by alexandru-paduraru** [comment]
@rodfraga thank you for using our product and sorry for the late response. We have in plan to support the migration for React but at this moment we don't have anybody specialized in our team to do that. Can you please share with us your current version and we will check the file structure to see what we can fix to make it work for you? Also please add the arrive.js library to support the generation of new checkboxes/radios/ripples etc. more about arrive in the original framework that we used: https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support

Keep in touch,
Alex

**Comment by rodfraga** [comment]
@alexandru-paduraru thanks for your reply, you can get the current project [family-kit](https://github.com/rodfraga/family-kit) I suggest to take the branch (dev) which has the more stable and recent code version, there you may find the following:

## changelog 

- React application working with Material-Dashbord Pro integrated (with some issues)
- Material-Dashboard css support for most components (wizard not tested yet)
- React Redux routing working (still has the preventDefault JavaScript render css issue)
- React Redux store and history browsing 
- React-Bootstrap-Material-Dashboard
- React- Google Material Design supported (not enabled yet)

Work needed, Google Maps integration, Chartist support (in this version) other not shared project has the support for Chartist. 

_tip: you can get the dashboard on the rout /dashboard in your localhost._

P.S. I can help you with the task of migrating to React if we can discuss about it.
Regards,
Rod

**Comment by alexandru-paduraru** [comment]
@rodfraga got it. Thank you for providing it. Can you please let us know how we start it? What do we need to install?

For the migration, that sounds very good. Let's talk in private all the details about the collaboration, alex@creative-tim.com

Keep in touch,
Alex
