### ISSUE TITLE
class="selectpicker" data-style="select-with-transition" - field not aligned

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/material-dashboard-pro#38]
Hi

I have a form with several fields and I want to use selectpicker with data-style="select-with-transition". Unfortunately this field is not aligned with the others. In the example below, the second field appears a few pix above the previous field. Any suggestion to fix this?

                                        <div class="col-sm-3">
                                            <div class="form-group label-floating">
                                                <label class="control-label">Zipcode</label>
                                                <input type="Zipcode" class="form-control" number="true" minlength="5" maxlength="5" required>
                                            </div>
                                        </div>

                                        <div class="col-sm-3">
                                            <select class="selectpicker" data-style="select-with-transition" title="State" data-size="7">
                                                <option disabled> Choose state</option>
                                                <option value="2">Florida </option>
                                                <option value="3">California</option>
                                                <option value="4">Massachusetts</option>
                                            </select>
                                        </div>

**Comment by alexandru-paduraru** [comment]
@EricL2017 thank you for pointing out. Please add at the end of your `assets/css/material-dashboard.css` this code 

```css
.form-group{
margin-top: 8px;
}
```
We will add this in the next update too.

Best,
Alex

**Comment by EricL2017** [comment]
Thank you Alex for fixing this issue. Great support!
