### ISSUE TITLE
Trouble creating checkbox in code

### ISSUE THREAD

**Issue by jdybowski** [creativetimofficial/material-dashboard-pro#46]
I need to dynamically create a list of items, each with a checkbox (I also store some data in the list for later processing). The following code works if I remove class="checkbox" from the initial div. It works if I embed the output as static html. If I run the code I don't get the checkbox but I do get the text. Can you tell me where I'm going wrong? Thanks.

                $('#equipmentList').append(
                    '<div class="checkbox">' +
                        '<label>' +
                            '<input type="checkbox" name="equipmentCheckboxes" checked' +
                            ' data-equipment_id=' + equipmentName +
                            ' data-equipment_disposition=' + equipmentDisposition +
                            ' data-timestamp=' + timestamp +
                            '>' +
                            equipmentName + ' - ' + equipmentDisposition + ' - ' + equipmentTime +
                        '</label>' +
                    '</div>');
                $('#equipmentList').trigger('create');

**Comment by dragosct10** [comment]
Hi @jdybowski! In this situation you add dynamically elements, so for fixing this you must include in your project at the bottom of the page where the `<script>` tags are located the library `arrive.js.` For more details about this library please visit this link: [Arrive.js](https://github.com/FezVrasta/bootstrap-material-design). Please let us know if everything is working fine! 

Regards,
Dragos

**Comment by jdybowski** [comment]
Thank you. My application uses much dynamic content. This approach makes it very simple to code. Working well.
