### ISSUE TITLE
How can i change the date time format?

### ISSUE THREAD

**Issue by harsha4446** [creativetimofficial/material-dashboard-pro#47]
Currently its a dd/mm/yyyy and i want to chnage it to yyyy-mm-dd
Could you please asssit?

**Comment by nexusnx** [comment]
Hey, how do u changed it?

**Comment by groovemen** [comment]
Hello @harsha4446,

Thank you for using our products, you have to set the date format when you initialize the datepicker: 
```
$('.datepicker').datepicker({
    format: 'mm/dd/yyyy'
})
```

All the best, 
Stefan
