### ISSUE TITLE
Keep menu open.

### ISSUE THREAD

**Issue by WildDylan** [creativetimofficial/material-dashboard-pro#48]
How to keep left side nav menu default open.

I set `aria-expanded="true"` to `<a>` and `<div>`, but it's not work.

**Comment by alexandru-paduraru** [comment]
@WildDylan thank you for using our product. Please make sure you add the class `.in` to the `.collapse` element that you want to have opened. Then everything will work fine. Like how we did in the `examples/components/buttons.html`

Best, Alex!

**Comment by WildDylan** [comment]
That works, thanks.
