### ISSUE TITLE
Scrolling on handheld devices over charts does not work.

### ISSUE THREAD

**Issue by JorgenSolli** [creativetimofficial/material-dashboard-pro#49]
Hey!

So it seems that you cant put your finger on a chart and scroll up/down/left/right. Some of my charts are fairly tall and the user is left with just a few pixels to scroll on. You can replicate this on any of the charts in the demo files btw, either on an actual phone or in dev tools device-view.

It seems that the guys over at Chartists have figured it out, as I don't have this issue on their Examples page, yet I can't find a single issue on their Github regarding this which makes me think we're doing something wrong?

If not then I'll probably open a issue there as well, but I thought I would start here as this is something you also should be aware of. If we cant resolve the issue, this pretty much means I cant use any charts of this kind in my app :(

**Comment by alexandru-paduraru** [comment]
@JorgenSolli thank you for pointing out. We've checked and it seems the touch is not working smooth with the svgs, a quick solution, till we will do more tests and verifications would be to add this code at the end of material-dashboard.css

```css
.ct-chart svg{
    position: relative;
    z-index: -1;
}
```

Then everything will work fine.

Best,
Alex

**Comment by JorgenSolli** [comment]
Thank you :) 
-1 hid it behind my card. but z-index: 0 did that trick.
