### ISSUE TITLE
Floating labels with input fields loaded from code

### ISSUE THREAD

**Issue by jdybowski** [creativetimofficial/material-dashboard-pro#50]
From time to time I have to pre-load certain input fields in a form using code. I would like floating labels to behave the same as they do when entering data from keyboard. How can I accomplish this?

Here I have inserted the user id and password using code and labels remain in default position. Company was entered from keyboard and gives desired result.

![image](https://user-images.githubusercontent.com/1773951/27413874-0346e61e-56cc-11e7-96c8-68e315e557e8.png)

**Comment by EricL2017** [comment]
Hi jdybowski,

I raised a similar question on the creative-tim.com site and someone said the issue is created by jquery. Below is the code that I added to fix the issue: 

if ("data to be populated"){$('#field').parent().removeClass("is-empty");};

Hope it works for you too!

**Comment by jdybowski** [comment]
EricL2017,

Thanks a million. Works great. Just what I was looking for.

**Comment by parkbsu** [comment]
I found this approach works better - 
`if (data.artifactName.length) { $('#artifactName').parent().addClass("is-filled"); };`

There's a strong likelihood I was using EricL2017's approach incorrectly though!
