### ISSUE TITLE
Selectpicker - Dynamic dropdown box - cannot add options from JQuery

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/material-dashboard-pro#51]
Hi
I am trying to dynamically add options to a dropdown box (class="selectpicker" data-style="select-with-transition"). It works fine if I put the code below in the html page (<script>), but when I put it in my JS file, it does no longer work. Also, it works fine from my JS file with regular dropdown box (class =""). Any idea how this can be fixed? 

var option = document.createElement('option');
option.value = "MN";
option.text = "Minessota";
document.getElementById('location-state').options.add(option);

**Comment by alexandru-paduraru** [comment]
@EricL2017 thank you for using our product. We are using Bootstrap Selectpicker (http://silviomoreto.github.io/bootstrap-select/) for a custom design of the regular select. That library is creating an extra dropdown with options and is hiding the regular select. 

When you add the data to the regular select, like how you add it in the upper example, you are basically adding to the select element the is hidden. You have to add it via the Selectpicker or refresh the selectpicker after you add the data to the hidden select. 

You can find more details about the update here: http://silviomoreto.github.io/bootstrap-select/methods/ and here other options to manipulate the data: http://silviomoreto.github.io/bootstrap-select/examples/

Let us know if that was helpful.

**Comment by EricL2017** [comment]
Hi Alex, thanks again for your advice. It works perfect! 

Fantastic support! Well done Alex.

**Comment by alexandru-paduraru** [comment]
Glad that it was working fine! I will keep the issue open so we will make the necessary updates in documentation for other customers too.

**Comment by luiscarcm** [comment]
Good evening, I have a problem with selectpicker, I do not can add new option with the data-content attribute from jquery, help me thanks
I tried:
$("#myselect").append('<option data-content="<span class='label label-success'>Relish</span>">Relish</option>');
$("#myselect").selectpicker("refresh");

**Comment by dragosct10** [comment]
Hi, @luiscarcm! To add dynamically options please use the `arrive.js` library that it's included in the product.

Regards, 
Dragos
