### ISSUE TITLE
selectpicker Dropdown With Large Number of Items Creating White Space at The Bottom of The Page

### ISSUE THREAD

**Issue by street1030** [creativetimofficial/material-dashboard-pro#54]
I have a selectpicker dropdown with around 100 items in it and the dropdowns size set to 5.  For each item in the list that extends beyond the constraints of the parent element, the page is extended.  This extra space goes away after clicking on the dropdown.  As you can see in the image below, after the page ends, white space is created to accommodate the dropdown items although they are not visible.  Keep in mind, the white space has not vanished in this screenshot because I have a second dropdown that has yet to be clicked (with the same amount of items in it).

![untitled](https://user-images.githubusercontent.com/17691864/27594294-3fc45720-5b0e-11e7-8a51-fdc279607f47.png)

**Comment by street1030** [comment]
This issue plagues almost every page that I'm using selectpicker on.  Anyone have any clue why this is happening?  I can't seem to pinpoint the cause of the issue.

**Comment by JorgenSolli** [comment]
I'm pretty sure this problem has something to do with _bootstrap select_ used in combination with _perfect-scrollbar_. I never tested it without the scrollbar, but one would think that such an obvious bug would be fixed or never even exist on something so popular and well made as bootstrap select. 

We gotta find a workaround ourselves for this issue I believe, but you COULD try and report it over at the [bootstrap select repo](https://github.com/silviomoreto/bootstrap-select/issues) and see if the author or any contributors are interested in committing a fix :)

**Comment by street1030** [comment]
I've disabled perfect scrollbar completely and the issue still persists.  We can scratch that one off the list of things to check.

**Comment by alexandru-paduraru** [comment]
@street1030 and @JorgenSolli we added some properties for the dropdowns in order to obtain a smooth transition from display: none to display: block and probably that is breaking some items. You can test this by going to `assets/scss/md/_dropdowns.scss` and remove anything that is between the lines 69 and 108. That is adding the transition to the dropdowns.

**Comment by street1030** [comment]
@alexandru-paduraru That seems to fix it!  Thanks Alex.
