### ISSUE TITLE
How to add event listener on datepicker?

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/material-dashboard-pro#56]
I added an event listener on a datepicker class ("onchange"). It works fine if the date is entered manually but it does not fire if the date is selected from the calendar. How should the event be set?

Thanks for your help!

**Comment by alexandru-paduraru** [comment]
@EricL2017 please check the examples: https://stackoverflow.com/questions/31858920/jquery-bootstrap-datetimepicker-change-event

Best,
Alex

**Comment by EricL2017** [comment]
Nice Alex! It worked fine. I added in my javascript file the following instruction:
$('#mydatepicker').on('dp.change', function(){ myfunction();});
