### ISSUE TITLE
Same issue as #54. Cannot execute the proposed solution

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/material-dashboard-pro#58]
Hi Alex

I have the same issue as #54. However I dont find the files that you mentioned in the proposed resolution. Can you please indicate where the files are located or resend a compiled material-dashboard.scss file?

Thanks
Eric

**Comment by alexandru-paduraru** [comment]
@EricL2017 thank you for letting us know and sorry for the late response, don't know how we missed this. Did you find the file `assets/scss/md/_dropdowns.scss` and removed anything between lines 69 and 108? Then compile `assets/scss/material-dashboard.scss` with the output to assets/css/material-dashboard.css using [Koala](http://koala-app.com/). Let us know your progress. 

Best,
Alex

**Comment by EricL2017** [comment]
Hi Alex

I was assuming you guys were on summer break…

Unfortunately, I cannot find the file structure you mention. See below how it looks like on my side. I don’t have a scss/md folder but a sass instead. If this seems correct to you, I will follow your instructions and try to re-compile. I will be out until the 8/20 but will follow up right there.

Thanks
Eric

**Comment by alexandru-paduraru** [comment]
@EricL2017 now I understand. We were looking at different versions of the product. We used to call the folder "scss" then we renamed it to "sass" for better language understanding http://sass-lang.com/. You can follow the same structure in sass. Let us know if that was working.

Best,
Alex

**Comment by EricL2017** [comment]
Thanks Alex. I will check when I'm back from vacation in a couple of weeks.

Eric
