### ISSUE TITLE
Multiple media files upload

### ISSUE THREAD

**Issue by cristian-chiric** [creativetimofficial/material-dashboard-pro#59]
Hi, 

Can you please provide a component to enable multiple media files (images and videos) for upload, similar to select image component?

Cheers,
Cris

**Comment by alexandru-paduraru** [comment]
@cristian-chiric thank you for using our product. Maybe this jQuery Plugin will help https://blueimp.github.io/jQuery-File-Upload/. Since it is using Bootstrap classes it will look as our Material Dashboard PRO design. 

Let us know your status.

Best,
Alex

**Comment by cristian-chiric** [comment]
@alexandru-paduraru thanks for the idea. Indeed, it will serve my purpose. 

Regards,
Cris
