### ISSUE TITLE
Styles bug in Datepicker inside Modal

### ISSUE THREAD

**Issue by MrJmpl3** [creativetimofficial/material-dashboard-pro#61]
The styles is bug in Datepicker input when is inside boostrap modal , the styles is gone

**Comment by MrJmpl3** [comment]
I solved , I still use datepicker instead datetimepicker ..

datepicker = Jquery UI
datetimepicker = Bootstrap Plugin

**Comment by alexandru-paduraru** [comment]
@MrJmpl3 thank you for pointing that out. Do you have an example of the version that is not working? In this way, we can check what is wrong there.

Best,
Alex

**Comment by MrJmpl3** [comment]
The wrong is me, sorry..

I used datepicker , but the correct usage is datetimepicker =D

**Comment by alexandru-paduraru** [comment]
no problem mate :D

**Comment by promaticsasif** [comment]
datetime picker not working when using material dashboard pro theme in the project
