### ISSUE TITLE
Initialize Switch button

### ISSUE THREAD

**Issue by caoquan95** [creativetimofficial/material-dashboard-pro#62]
Hi,

I cannot find any ways to initialize the switch button?

**Comment by alexandru-paduraru** [comment]
@caoquan95 thank you for using our product and sorry for the late response. The switches are initialized inside `$.material.init();` function. The core is inside material.min.js and that is coming from https://github.com/FezVrasta/bootstrap-material-design

If you have elements that are inserted in page after the first initialization, please add the Arrive.js library: https://github.com/FezVrasta/bootstrap-material-design/tree/master#arrivejs-support

Hope this helps.

Best,
Alex
