### ISSUE TITLE
Navbar issue in Paper Kit 2

### ISSUE THREAD

**Issue by jdybowski** [creativetimofficial/material-dashboard-pro#80]
Navbar navigation is either directly via links in header or using the dropdown list on smaller screens. At screen width of 768 neither of these options is available.

![image](https://user-images.githubusercontent.com/1773951/32411161-709ca142-c1aa-11e7-9fb0-595fa4e51fbd.png)

**Comment by alexandru-paduraru** [comment]
@jdybowski thank you for the information. Please open the issue on the product's repo: https://github.com/creativetimofficial/paper-kit. This is the repo for Material Dashboard PRO.

Best,
Alex

**Comment by jdybowski** [comment]
Hi Alex

Thank you for pointing out my mistake. I will go to the correct repo.

Thanks, John
