### ISSUE TITLE
Unable to close notification's modal on mobile

### ISSUE THREAD

**Issue by MahmoudLR** [creativetimofficial/material-dashboard-pro#83]
when I open a notification modal on mobile (iphone), I can not close it because there is an "overflow " on <body>;

**Comment by MahmoudLR** [comment]
http://demos.creative-tim.com/material-dashboard-pro/examples/components/notifications.html

**Comment by tahitiangabriel** [comment]
The same thing happens to me. 
It happens only on iphone/ipad with safari.
It works perfectly on my PC (chrome) and on android (chrome).

**Comment by dragosct10** [comment]
Hi! Thank you for using our product. To fix this issue please take all the divs with the class  `.modal ` from notifications.html page and put all of them out of the tag `body`. 

Regards,
Dragos

**Comment by MahmoudLR** [comment]
It works perfectly,
Thank you :)

**Comment by tahitiangabriel** [comment]
Sorry to come back late on this topic, but I'm using a dynamic framework with templates and it is not possible to add datas outside of the body tag.
Also having divs outside the body tag is not valid HTML5 even if it works.

**Comment by tahitiangabriel** [comment]
Hi,

This solve the problem.
Thank you for your help.

Regards,
Gabriel.
