### ISSUE TITLE
Side bar - sub menu not opening when collapsed

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/material-dashboard-pro#85]
Hi, 

I have downloaded the latest version of Material-dashboard-pro and I have an issue with the side bar. When collapsed (using the top menu option), the side bar does not longer work properly and the sub-menus do not open.

See below the examples:
Before (previous version)
<img width="267" alt="screen shot 2017-12-02 at 10 36 46 am" src="https://user-images.githubusercontent.com/28696680/33517607-d6d82140-d74c-11e7-998f-a623f493752b.png">

After (newest version) - the profile menu does not open
<img width="257" alt="screen shot 2017-12-02 at 10 32 51 am" src="https://user-images.githubusercontent.com/28696680/33517614-efde7a7c-d74c-11e7-85fd-914e17a16b6e.png">

Any idea how this can be corrected?
Thanks

**Comment by EricL2017** [comment]
Hi - any update on this issue? For information, the side bar works well when the window's size is reduced and the menu automatically collapses on the right part of the screen (see below)
<img width="242" alt="screen shot 2017-12-09 at 5 20 53 pm" src="https://user-images.githubusercontent.com/28696680/33800452-64c9c61c-dd05-11e7-93cd-df61850cb47d.png">

**Comment by EricL2017** [comment]
Closed by mistake...

**Comment by dragosct10** [comment]
Hi, @EricL2017! Sorry for the late response and thank you for using our product. Please, can you give us a link to your project because in this way it's hard to figure out what happened there?

Regards,
Dragos

**Comment by EricL2017** [comment]
Hi Dragos

Thanks for your message. Please check on www.uflex.work <http://www.uflex.work/> and log in as a candidate. You can use the account test@test.com <mailto:test@test.com>, password 123. 

Let me know if you need anything else.

Thanks a lot for your assistance!
Eric

**Comment by dragosct10** [comment]
Hi, @EricL2017! I found the problem and is coming from the `assets/js/material-dashboard.js ` because you have updated your product but you don't updated also the material-dashboard.js because the file is still have the version `1.1.0` and you working with the version `1.2.0` and also I noticed that you have two tags with maps and you have an error because of it in the console. 

Regards,
Dragos

**Comment by EricL2017** [comment]
Wonderful! Thanks a lot Dragos for your help. This is greatly appreciated! I have deployed the version 1.2.0 and the issue is now fixed!

Great support, as usual.
Eric
